config/routes.rb
Rails.application.routes.draw do

  namespace :end_users do
    get 'categories/:id', to: "categories#show", :as => :categories_show
  end

  scope module: :end_users do
    get ':end_users_id/destinations', to: 'destinations#index', :as => :destinations_index
    patch ':end_users_id/destinations', to: 'destinations#update', :as => :destinations_update
    get ':end_users_id/destinations/:id/edit', to: 'destinations#edit', :as => :destinations_edit
    delete ':end_users_id/destinations/:id', to: 'destinations#destroy', :as => :destinations_destroy
    post ':end_users_id/destinations', to: 'destinations#create', :as => :destinations_create
  end
  namespace :admins do
    get 'categories', to: "categories#index"
    get 'categories/:id', to: "categories#edit"
    post 'categories', to: "categories#create", :as => :categories_create
    patch 'categories/:id', to: "categories#update", :as => :categories_update
  end
  namespace :admins do
    patch 'orders/:id', to: "orders#update", :as => :orders_update
    get 'orders/:id', to: "orders#show", :as => :orders_show
    get 'orders/', to: "orders#index", :as => :orders_index
  end

  namespace :admins do
    patch 'orderdetail/:id', to: "orders#detailup", :as => :detail_update
  end

  namespace :admins do
    get 'items/', to: 'items#index'
    get 'items/new', to: 'items#new', :as => :item_new_path
    get 'items/:id', to: 'items#show', :as => :item_show_path
    patch 'items/:id', to: 'items#update', :as => :item_update
    get 'items/:id/edit', to: 'items#edit', :as => :item_edit
    post 'items/', to: 'items#create', :as => :item_create
  end


    get "items/:id", to: "items#show", :as => :items_show

  namespace :admins do
    get 'end_users/', to: 'end_users#index', :as => :end_users_index
    get 'end_users/:id/edit', to: 'end_users#edit', :as => :end_users_edit
    get 'end_users/:id', to: 'end_users#show', :as => :end_users_show
    patch 'end_users/:id', to: 'end_users#update'
  end

  namespace :admins do
    get 'sales/', to: 'sales#index', :as => :sales
    get 'sales/view', to: 'sales#view', :as => :sales_view
  end

  scope module: :end_users do
    get 'orders/new', to: 'orders#new', :as => :orders_new
    post 'orders/new', to: 'orders#create', :as => :orders_create
    get 'orders/confirm', to: 'orders#confirm', :as => :orders_confirm
    post 'orders/confirm', to: 'orders#sending', :as => :orders_send
    delete 'orders/:id', to: 'orders#destroy', :as => :orders_destroy
    get 'orders/thanks' => 'orders#thanks'
    get 'orders/index'
    get 'orders/:id', to: 'orders#show', :as => :orders_show
  end

  root to: "end_users/top#index"
  get '/admins', to: 'admins/top#index', :as => :admins_root
  get '/end_users/close', to: 'end_users#bye', :as => :end_users_bye
  patch '/end_users/close', to: 'end_users#close'
  get '/about/', to: 'end_users/top#about'
  get '/end_users/mypage', to: 'end_users#mypage'
  get '/end_users/edit', to: 'end_users#edit'
  patch '/end_users/edit', to: 'end_users#update'
  put '/end_users/edit', to: 'end_users#update'
  get '/end_users/password', to: 'end_users#password', :as => :end_users_password
  get '/end_users/password/changed', to: 'end_users#changed', :as => :end_users_changed

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}

devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}

  get '/carts', to: 'carts#index'
  patch'/carts', to: 'carts#update'
  delete'/carts/:id', to: 'carts#destroy', :as => :carts_destroy
  delete'/carts/', to: 'carts#empty', :as => :carts_empty
  post '/items/:id', to: 'carts#create', :as => :carts_add

  get '/search', to: 'search#index', :as => :search
  get '/review', to: 'reviews#index', :as => :review
  get '/review/pos', to: 'reviews#pos', :as => :review_pos
  patch '/review/pos', to: 'reviews#update', :as => :review_update
end

app/models/cart.rb
class Cart < ApplicationRecord

belongs_to :end_user
belongs_to :item
validates :item_quantity, numericality: {only_integer: true, greater_than_or_equal_to: 1}


end

app/controllers/admins/carts_controller.rb
class Admins::CartsController < ApplicationController
	before_action :authenticate_admin!
	before_action :header_login_check
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :header_login_check
	def index
		@cart_total_price = 0
		@cart_items = current_end_user.carts
	  @cart_items.each do |cart|
		@cart_total_price += (cart.item.price) * (cart.item_quantity) * 1.10
	  end
	end

	def create
		@cart_item = current_end_user.carts.find_by(item_id: params[:id])
	  if @cart_item.blank?
		item = Item.find(params[:id])
		cart_item = Cart.new(item_id:item.id,end_user_id:current_end_user.id,item_quantity:params[:cart][:item_quantity])
		cart_item.save
		redirect_to carts_path
		flash[:notice] = "カートに商品を追加しました！"
	  else
	    @cart_item.item_quantity += 1
		@cart_item.save
		redirect_to carts_path
	  end
	end

	def update
		@cart_item = Cart.find(cart_params[:id])
		if @cart_item.update(cart_params)
			redirect_to carts_path
			flash[:notice] = "カートの商品を更新しました！"
		else render :index
		end
	end


	def destroy
		@cart_item = Cart.find(params[:id])
		@cart_item.destroy
		redirect_to carts_path
		flash[:notice] = "カートの商品を削除しました！"
	end


	def empty
		@cart_items = Cart.where(end_user_id:current_end_user)
		@cart_items.destroy_all
		redirect_to carts_path
		flash[:notice] = "カートを空にしました！"
	end

private

	def cart_params
		params.require(:cart).permit(:item_quantity, :id, :item_id, :end_user_id)
	end



end

app/controllers/end_users/carts_controller.rb
class EndUsers::CartsController < ApplicationController
  before_action :header_login_check

  def index

  end

  def create
  end

  def destroy
  end

  def update
  end

  def empty
  end


end

app/helpers/admins/carts_helper.rb
module Admins::CartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/end_users/carts_helper.rb
module EndUsers::CartsHelper
end

app/views/carts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
</head>
<div class = "container">
	<body>

		<h1>ショッピングカート</h1><br>
		<div class ="pull-right">
	<% if current_end_user.carts.count > 0  %>
			<h2><%= link_to 'カートを空にする', carts_empty_path, method: :delete, data:{confirm: 'カートを空にして本当によろしいですか？'}, class: "btn-lg btn-danger" %></h2></br>
		</div>

		<div class = "row">
			<div class ="col-xs-12">
				<table class ="table table-bordered">
					<thead>
						<tr>
							<th>商品名</th>
							<th>単価(税込)</th>
							<th>数量</th>
							<th>小計</th>
							<th></th>
						</tr>
					</thead>
					<% current_end_user.carts.each do |cart| %>
					　<tbody>
						<tr>
							<td><%= attachment_image_tag cart.item, :image, :fill, 50, 50, class: "", fallback: "noimage.jpg",size:'50x50'%><%= cart.item.name %></td>
							<td><%= (cart.item.price * 1.10).to_i.to_s(:delimited) %></td>
							<%= form_for (cart), url: carts_path do |f| %>
							<td><%= f.number_field :item_quantity, class: "qtty", min: 1, max: 99%><%= f.submit '更新', class: "btn-sm btn-success"%></td>
							<%= f.hidden_field :id, :value => cart.id %>
							<td><%= (cart.item.price * 1.10 * cart.item_quantity).to_i.to_s(:delimited) %>円 </td>
							<% end %>
							<td><%= link_to '削除', carts_destroy_path(cart.id), method: :delete, class: "btn-sm btn-danger" %></td>
						</tr>
					　</tbody>
					<% end %>
				</table>
			</div>
		</div>
		<td><%= link_to '買い物を続ける',root_path, class: "btn-lg btn-info" %></td><br>

  		  <div class ="pull-right">
		    <table class = "table table-bordered">
			<tr>
				<td><h2>合計金額</h2></td>
					<td><h2><%= @cart_total_price.to_i.to_s(:delimited)%>円</h2></td>
			</tr>
		    </table>
		  </div><br><br><br><br><br>
		<div class ="col-xs-5 col-xs-offset-3">
		<%= link_to '情報入力に進む', orders_new_path, class: "btn btn-info btn-lg btn-block"  %>
	<% else %>
		<div class = "container">
			<div class ="col-xs-12">
				<div class="pull-left">
					<h1>カートは空です</h1><br>
					<%= link_to '買い物を続ける',root_path, class: "btn-lg btn-info" %>
				</div>
			</div>
		</div>
	 </div>
	<% end %>
		</body>
</div>
				</html>