config/routes.rb
Rails.application.routes.draw do

  namespace :end_users do
    get 'categories/:id', to: "categories#show", :as => :categories_show
  end

  scope module: :end_users do
    get ':end_users_id/destinations', to: 'destinations#index', :as => :destinations_index
    patch ':end_users_id/destinations', to: 'destinations#update', :as => :destinations_update
    get ':end_users_id/destinations/:id/edit', to: 'destinations#edit', :as => :destinations_edit
    delete ':end_users_id/destinations/:id', to: 'destinations#destroy', :as => :destinations_destroy
    post ':end_users_id/destinations', to: 'destinations#create', :as => :destinations_create
  end
  namespace :admins do
    get 'categories', to: "categories#index"
    get 'categories/:id', to: "categories#edit"
    post 'categories', to: "categories#create", :as => :categories_create
    patch 'categories/:id', to: "categories#update", :as => :categories_update
  end
  namespace :admins do
    patch 'orders/:id', to: "orders#update", :as => :orders_update
    get 'orders/:id', to: "orders#show", :as => :orders_show
    get 'orders/', to: "orders#index", :as => :orders_index
  end

  namespace :admins do
    patch 'orderdetail/:id', to: "orders#detailup", :as => :detail_update
  end

  namespace :admins do
    get 'items/', to: 'items#index'
    get 'items/new', to: 'items#new', :as => :item_new_path
    get 'items/:id', to: 'items#show', :as => :item_show_path
    patch 'items/:id', to: 'items#update', :as => :item_update
    get 'items/:id/edit', to: 'items#edit', :as => :item_edit
    post 'items/', to: 'items#create', :as => :item_create
  end


    get "items/:id", to: "items#show", :as => :items_show

  namespace :admins do
    get 'end_users/', to: 'end_users#index', :as => :end_users_index
    get 'end_users/:id/edit', to: 'end_users#edit', :as => :end_users_edit
    get 'end_users/:id', to: 'end_users#show', :as => :end_users_show
    patch 'end_users/:id', to: 'end_users#update'
  end

  namespace :admins do
    get 'sales/', to: 'sales#index', :as => :sales
    get 'sales/view', to: 'sales#view', :as => :sales_view
  end

  scope module: :end_users do
    get 'orders/new', to: 'orders#new', :as => :orders_new
    post 'orders/new', to: 'orders#create', :as => :orders_create
    get 'orders/confirm', to: 'orders#confirm', :as => :orders_confirm
    post 'orders/confirm', to: 'orders#sending', :as => :orders_send
    delete 'orders/:id', to: 'orders#destroy', :as => :orders_destroy
    get 'orders/thanks' => 'orders#thanks'
    get 'orders/index'
    get 'orders/:id', to: 'orders#show', :as => :orders_show
  end

  root to: "end_users/top#index"
  get '/admins', to: 'admins/top#index', :as => :admins_root
  get '/end_users/close', to: 'end_users#bye', :as => :end_users_bye
  patch '/end_users/close', to: 'end_users#close'
  get '/about/', to: 'end_users/top#about'
  get '/end_users/mypage', to: 'end_users#mypage'
  get '/end_users/edit', to: 'end_users#edit'
  patch '/end_users/edit', to: 'end_users#update'
  put '/end_users/edit', to: 'end_users#update'
  get '/end_users/password', to: 'end_users#password', :as => :end_users_password
  get '/end_users/password/changed', to: 'end_users#changed', :as => :end_users_changed

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}

devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}

  get '/carts', to: 'carts#index'
  patch'/carts', to: 'carts#update'
  delete'/carts/:id', to: 'carts#destroy', :as => :carts_destroy
  delete'/carts/', to: 'carts#empty', :as => :carts_empty
  post '/items/:id', to: 'carts#create', :as => :carts_add

  get '/search', to: 'search#index', :as => :search
  get '/review', to: 'reviews#index', :as => :review
  get '/review/pos', to: 'reviews#pos', :as => :review_pos
  patch '/review/pos', to: 'reviews#update', :as => :review_update
end

app/models/item.rb
class Item < ApplicationRecord
	attachment :image
	belongs_to :category
	has_many :carts, dependent: :destroy
	has_many :orders, through: :order_details, source: :order
	validates :price, numericality: { only_integer: true, greater_than: 0}
	def self.search(search)
      return Item.all unless search
      Item.where(['name LIKE ?', "%#{search}%"])
  	end
  	validates :name, presence: true
  	validates :discription, presence: true
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :header_login_check
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @price_zeikomi = (@item.price * 1.10).to_i
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '商品の編集に成功しました。'
      redirect_to admins_item_show_path_path(@item)
    else
      @item = Item.find(params[:id])
      @categories = Category.all
      flash[:notice] = '商品の編集に失敗しました。'
      render :edit
    end
  end

  def new
    @item = Item.new
    @categories = Category.all
  end

  def create
      @item = Item.new(item_params)
      @item.sort_item = 0
      if @item.save
        flash[:notice] = '商品の作成に成功しました。'
        redirect_to admins_items_path
      else
        @item = Item.new
        @categories = Category.all
        flash[:notice] = '商品の作成に失敗しました。'
        render :new
      end
  end

  def item_params
      params.require(:item).permit(:name, :price, :discription, :image, :category_id, :status)
  end
end

app/controllers/end_users/items_controller.rb
class EndUsers::ItemsController < ApplicationController
	before_action :header_login_check
  def index
  	  @item = Item.new
  	  @items = Item.all
  end

  def show
  	  @item = Item.find(params[:id])
  	  @price_zeikkomi = @item.price * 1.10
  end

  def item_params
      params.require(:item).permit(:name, :price, :discription, :image)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :header_login_check
  def index
      @item = Item.new
      @items = Item.all
  end

  def show
      @item = Item.find(params[:id])
      @price_zeikomi = (@item.price * 1.10)
      @cart = Cart.new
      @categories = Category.where(available: true)
  end

  def item_params
      params.require(:item).permit(:name, :price, :discription, :image, :category_id)
  end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<%= form_for @item, url: admins_item_update_path(@item) do |f| %>
<div class="container">
        <h2>商品編集画面</h2>
        <div class="item-image">
            <%= attachment_image_tag @item, :image, :fill, 200, 200, class: "img-circle pull-left profile-thumb", fallback: "noimage.jpg",size:'200x200'%>
        </div>
        <div class="form-group has-icon">
        <%= f.attachment_field :image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        </div>
        <div class="form-group row">
        <label for="item_name">商品名</label><br>
        <%= f.text_field :name, class:'col-xs-12' %>
      </div>
      <div class="form-group row">
        <label for="item_discription">商品説明</label><br>
        <%= f.text_area :discription, class:'col-xs-12' %>
      </div>
      <div class="form-group row">
        <label for="category_id">ジャンル</label><br>
        <%= f.collection_select(:category_id, @categories, :id, :name) %>
      </div>
      <div class="form-group row">
        <label for="item_price">税抜き価格</label><br>
        <%= f.number_field :price, class:'col-xs-12' %>
      </div>
      <div class="form-group row">
        <select name="item[status]" id="item_status"><option value="1">販売中</option>
    <option value="0">販売停止中</option></select>
      </div>
      </div>
</div>
<%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
<h1>商品一覧画面</h1>
<div class="pull-right">
<%= link_to "新規登録", admins_item_new_path_path, class:'btn btn-info btn-md' %>
</div>
  <div class="col-xs-12">
<table class="table table-responsive table-bordered">
<thead>
    <tr class="active">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <br>
  <tbody>
      <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admins_item_show_path_path(item) %></td>
      <td><%= (item.price).to_s(:delimited) %></td>
      <td><%= item.category.name %></td>
      <% if item.status %>
      	<td>販売中</td>
      <% else %>
        <td>販売停止中</td>
      <% end %>
    </tr>
  <% end %>
</tbody>
</table>
</div>
<div class="col-xs-2">
</div>
</div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row">
<h1>商品 新規登録画面</h1>
<%= form_for @item, url: admins_item_create_path do |f| %>
   <div class="form-group has-icon">
    <%= f.attachment_field :image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>
  <div class="form-group row">
    <label for="item_name">商品名</label><br>
    <%= f.text_field :name, class:'col-xs-12' %>
  </div>
  <div class="form-group row">
    <label for="item_discription">商品説明</label><br>
    <%= f.text_area :discription, class:'col-xs-12' %>
  </div>
  <div class="form-group row">
    <%= f.collection_select(:category_id, @categories, :id, :name) %>
  </div>
  <div class="form-group row">
    <label for="item_price">税抜き価格</label><br>
    <%= f.number_field :price, class:'col-xs-12' %>
  </div>
  <div class="form-group row">
    <select name="item[status]" id="item_status"><option value="1">販売中</option>
<option value="0">販売停止中</option></select>
  </div>
  <div class="actions row">
    <%= f.submit '新規登録', class:'btn btn-info col-xs-12' %>
  </div>
<% end %>
</div>
</div>

app/views/admins/items/show.html.erb
<div class ="container">
  <h1>商品　詳細画面</h1>
  <div class ="row">
    <div class ="col-xs-3">
      <div class="item-image">
        <%= attachment_image_tag @item, :image, :fill, 200, 200, class: "", fallback: "noimage.jpg",size:'200x200'%>
    </div>
    </div>
    <div class ="col-xs-5">
    <table class = "table">
      <tr>
        <td><h2>商品名</h2></td><td><h2><%= @item.name %></h2></td>
      </tr>
      <tr>
        <td><h2>商品説明</h2></td><td><h2><%= @item.discription %></h2></td>
      </tr>
      <tr>
        <td><h2>ジャンル</h2></td><td><h2><%= @item.category.name %></h2></td>
      </tr>
      <td><h2>税抜き価格</h2></td><td><h2><%= @item.price.to_s(:delimited)%></h2></td>
      <tr>
        <td><h2>税込み価格</h2></td><td><h2><%= @price_zeikomi.to_s(:delimited)%></h2></td>
      </tr>
      <tr>
        <td><h2>販売ステータス</h2></td><% if @item.status %>
        <td><h2>販売中</h2></td><br>
        <% else %>
        <td><h2>販売停止中</h2></td><br>
        <% end %>
      </tr>
    </table>
    <div class ="pull-right">
      <%= link_to "編集する", admins_item_edit_path(@item), class: "btn btn-info btn-lg" %>
    </div>
  </div>
</div>