config/routes.rb
Rails.application.routes.draw do

  namespace :end_users do
    get 'categories/:id', to: "categories#show", :as => :categories_show
  end

  scope module: :end_users do
    get ':end_users_id/destinations', to: 'destinations#index', :as => :destinations_index
    patch ':end_users_id/destinations', to: 'destinations#update', :as => :destinations_update
    get ':end_users_id/destinations/:id/edit', to: 'destinations#edit', :as => :destinations_edit
    delete ':end_users_id/destinations/:id', to: 'destinations#destroy', :as => :destinations_destroy
    post ':end_users_id/destinations', to: 'destinations#create', :as => :destinations_create
  end
  namespace :admins do
    get 'categories', to: "categories#index"
    get 'categories/:id', to: "categories#edit"
    post 'categories', to: "categories#create", :as => :categories_create
    patch 'categories/:id', to: "categories#update", :as => :categories_update
  end
  namespace :admins do
    patch 'orders/:id', to: "orders#update", :as => :orders_update
    get 'orders/:id', to: "orders#show", :as => :orders_show
    get 'orders/', to: "orders#index", :as => :orders_index
  end

  namespace :admins do
    patch 'orderdetail/:id', to: "orders#detailup", :as => :detail_update
  end

  namespace :admins do
    get 'items/', to: 'items#index'
    get 'items/new', to: 'items#new', :as => :item_new_path
    get 'items/:id', to: 'items#show', :as => :item_show_path
    patch 'items/:id', to: 'items#update', :as => :item_update
    get 'items/:id/edit', to: 'items#edit', :as => :item_edit
    post 'items/', to: 'items#create', :as => :item_create
  end


    get "items/:id", to: "items#show", :as => :items_show

  namespace :admins do
    get 'end_users/', to: 'end_users#index', :as => :end_users_index
    get 'end_users/:id/edit', to: 'end_users#edit', :as => :end_users_edit
    get 'end_users/:id', to: 'end_users#show', :as => :end_users_show
    patch 'end_users/:id', to: 'end_users#update'
  end

  namespace :admins do
    get 'sales/', to: 'sales#index', :as => :sales
    get 'sales/view', to: 'sales#view', :as => :sales_view
  end

  scope module: :end_users do
    get 'orders/new', to: 'orders#new', :as => :orders_new
    post 'orders/new', to: 'orders#create', :as => :orders_create
    get 'orders/confirm', to: 'orders#confirm', :as => :orders_confirm
    post 'orders/confirm', to: 'orders#sending', :as => :orders_send
    delete 'orders/:id', to: 'orders#destroy', :as => :orders_destroy
    get 'orders/thanks' => 'orders#thanks'
    get 'orders/index'
    get 'orders/:id', to: 'orders#show', :as => :orders_show
  end

  root to: "end_users/top#index"
  get '/admins', to: 'admins/top#index', :as => :admins_root
  get '/end_users/close', to: 'end_users#bye', :as => :end_users_bye
  patch '/end_users/close', to: 'end_users#close'
  get '/about/', to: 'end_users/top#about'
  get '/end_users/mypage', to: 'end_users#mypage'
  get '/end_users/edit', to: 'end_users#edit'
  patch '/end_users/edit', to: 'end_users#update'
  put '/end_users/edit', to: 'end_users#update'
  get '/end_users/password', to: 'end_users#password', :as => :end_users_password
  get '/end_users/password/changed', to: 'end_users#changed', :as => :end_users_changed

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}

devise_for :end_users, controllers: {
  sessions:      'end_users/sessions',
  passwords:     'end_users/passwords',
  registrations: 'end_users/registrations'
}

  get '/carts', to: 'carts#index'
  patch'/carts', to: 'carts#update'
  delete'/carts/:id', to: 'carts#destroy', :as => :carts_destroy
  delete'/carts/', to: 'carts#empty', :as => :carts_empty
  post '/items/:id', to: 'carts#create', :as => :carts_add

  get '/search', to: 'search#index', :as => :search
  get '/review', to: 'reviews#index', :as => :review
  get '/review/pos', to: 'reviews#pos', :as => :review_pos
  patch '/review/pos', to: 'reviews#update', :as => :review_update
end

app/controllers/admins/sales_controller.rb
class Admins::SalesController < ApplicationController
	before_action :header_login_check
	before_action :authenticate_admin!
	def index
	end
	def view
		case params[:method]
		when "1"
			to = Time.current
			case params[:between]
			when "1"
				from = Time.current.strftime('%Y-%m-%d')
				b_from = (Time.current - 1.days).strftime('%Y-%m-%d')
				@label1="今日"
				@label2="昨日"
				@label3="前日比"
			when "2"
				from = to.beginning_of_week(start_day = :sunday)
				b_from = (Time.current - 1.weeks).beginning_of_week(start_day = :sunday)
				@label1="今週"
				@label2="先週"
				@label3="前週比"
			when "3"
				from = to.beginning_of_month
				b_from = (Time.current - 1.months).beginning_of_month
				@label1="今月"
				@label2="先月"
				@label3="前月比"
			when "4"
				from = to.beginning_of_year
				b_from = (Time.current - 1.years).beginning_of_year
				@label1="今年"
				@label2="昨年"
				@label3="前年比"
			end
			@orders = Order.where(:created_at=> from..to)
			@last_orders = Order.where(:created_at=> b_from..from)
			@charge_sum = 0
			@orders.each do |order|
				@charge_sum += order.charge
			end
			@last_charge_sum = 0
			@last_orders.each do |lastorder|
				@last_charge_sum += lastorder.charge
			end
			@dif = @charge_sum - @last_charge_sum
			@orders_count = @orders.count
			@last_orders_count = @last_orders.count
			@count_dif = @orders_count - @last_orders_count
		when "2"
			from = params[:start_day]
			to = params[:finish_day]
		end
			@orders = Order.where(:created_at=> from..to)
			@charge_sum = 0
			@orders.each do |order|
				@charge_sum += order.charge
			end
			@orders_count = @orders.count
	end
end

app/helpers/admins/sales_helper.rb
module Admins::SalesHelper
end

app/views/admins/sales/index.html.erb
<div class="container">
	<h1>売上管理画面</h1>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
<%= form_tag(admins_sales_view_path, method: :get, data: { remote: false }) do %>
  <h2>期間を選択する</h2>
  <%= radio_button_tag :method,1,true %>
  <%= select_tag :between, options_for_select([["今日","1"], ["今週","2"], ["今月","3"], ["今年","4"]],:selected=>"1") %>
  <h2>・期間を直接指定する</h2>
  <%= radio_button_tag :method,2,false %>
  <div class="row">
  	<div class="col-xs-6">
  <%= date_field_tag :start_day, {}, class: 'form-control' %><label>から</label>
  	</div>
  	<div class="col-xs-6">
  <%= date_field_tag :finish_day, {}, class: 'form-control' %><label>まで</label>
  	</div>
</div>
  <%= submit_tag '表示', :name => nil, class:'btn btn-success' %>
<% end %>
</div>
<div class="col-xs-3">
	</div>
</div>
</div>

app/views/admins/sales/view.html.erb
<div class="container">
	<h1>売上管理画面</h1>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
<table class="table table-bordered">
	<thead>
		<tr class="active">
			<th></th>
			<% if params[:method] == "2" then %>
				<th><%= params[:start_day] %>から<%= params[:finish_day] %>までの期間</th>
			<% else %>
			<th><%= @label1 %></th>
			<th><%= @label2 %></th>
			<th><%= @label3 %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>売上</th>
			<th><%= @charge_sum.to_s(:delimited) %>円</th>
			<% if params[:method] == "1" %>
			<th><%= @last_charge_sum.to_s(:delimited) %>円</th>
			<% if @dif < 0 then %>
				<th class="danger"><%= @dif.to_s(:delimited) %>円</th>
			<% elsif @dif == 0 %>
				<th class="info">±<%= @dif.to_s(:delimited) %>円</th>
			<% else %>
				<th class="success">+<%= @dif.to_s(:delimited) %>円</th>
			<% end %>
			<% end %>
		</tr>
		<tr>
			<th>注文件数</th>
			<th><%= @orders_count %>件</th>
			<% if params[:method] == "1" %>
			<th><%= @last_orders_count %>件</th>
			<% if @count_dif < 0 then %>
				<th class="danger"><%= @count_dif %>件</th>
			<% elsif @count_dif == 0 %>
				<th class="info">±<%= @count_dif %>件</th>
			<% else %>
				<th class="success">+<%= @count_dif %>件</th>
			<% end %>
			<% end %>
		</tr>
	</tbody>
</table>
<%= link_to "戻る", admins_sales_path, class:'btn btn-warning' %>
</div>
<div class="col-xs-3">
</div>
</div>
</div>